#!/usr/bin/env ruby
# -*- mode: ruby; coding: utf-8 -*-

require 'fileutils'

DELETE_LIST_REGEX = ["\w*~$", "^\\#.*", "^a\\.exe.*", "^a\\.out$", ".*\\.class$"];

def removeFilesRecursively(files)
  files.each do |file|
    Dir.glob("#{file}/**/*") do |f|
      deleteFile(f) unless File.directory?(f)
    end
  end
end

def removeFile
  Dir.glob("*") do |f|
    deleteFile(f) unless File.directory?(f)
  end
end

def deleteFile(f)
  DELETE_LIST_REGEX.each do |word|
    if /#{word}/ =~ File.basename(f)
      FileUtils.rm f
    end
  end
end

def main
  begin
    if ARGV.length < 1
      removeFile
    elsif
      removeFilesRecursively(ARGV)
    end
  rescue
    puts "error"
  end
end


main


